### ISSUE TITLE
indent_style doesn't work with editor.insertSpaces: "auto"

### ISSUE THREAD

**Issue by Zoltu** [Microsoft/vscode-editorconfig#12] opened 2016-01-02 21:55 UTC
I want VS Code to default to doing whatever the file already does unless an `.editorconfig` is present.  However, if you have `"editor.insertSpaces": "auto"` in your VSCode `settings.json` and `indent_style = tab` in your `.editorconfig`, new files that match the `.editorconfig` file matcher end up using spaces (the VS Code fallback for new files) rather than the `.editorconfig` settings.

**Comment by egamma** [comment] 2016-01-04 09:03
CC @chrisdias @alexandrudima

**Comment by SamVerschueren** [comment] 2016-02-11 09:48
This is a somewhat a duplicate of #19 I guess. Or #19 is a duplicate of this one. Because of slow response times by the authors which are probably too busy to update the core VS Code, we forked this repository to https://github.com/editorconfig/editorconfig-vscode and released under a new plugin. When https://github.com/editorconfig/editorconfig-vscode/pull/5 lands in that repo, this is fixed.

**Comment by jedmao** [comment] 2016-02-11 19:05
Which will probably be sometime in the next 24 hours.

**Comment by chrisdias** [comment] 2016-03-08 10:52
closing

**Closed by chrisdias** 2016-03-08 10:52 UTC
