### ISSUE TITLE
insert_final_newline into editorconfig file

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode-editorconfig#18] opened 2016-01-19 12:47 UTC
My `.editorconfig` file looks like this:

```ini
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 4
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true

[package.json]
indent_size = 2
```

If I save it, a final newline is not added.

**Comment by peterblazejewicz** [comment] 2016-02-10 22:08
@glen-84 
Make sure you're using latest version of extension. This feature seems to work fine:
https://github.com/Microsoft/vscode-editorconfig/commit/baba53fffb661f2f9234b26ee626ac45aadda0e0

**Comment by jedmao** [comment] 2016-02-10 22:18
I think it's because the file isn't saved yet, so it has no editorconfig configuration to read. This is a, "What came first? The chicken or the egg?" scenario.

**Comment by glen-84** [comment] 2016-02-11 07:19
@peterblazejewicz I'm using the latest version, and I just tested it again and it still doesn't work. Please note that I'm referring to saving the editorconfig file itself, not another file.

@jedmao If I save the file with `insert_final_newline = true` and then edit something and save it again, it still doesn't insert the newline.

**Comment by jedmao** [comment] 2016-02-11 08:36
@glen-84 I am able to reproduce this issue on my fork, [`editorconfig/editorconfig-vscode`](https://github.com/editorconfig/editorconfig-vscode) as well.

**Comment by jedmao** [comment] 2016-02-12 10:21
@glen-84 this is fixed in https://github.com/editorconfig/editorconfig-vscode/issues/9. Use the forked extension and it should work for you. You can thank @SamVerschueren for the fix.

**Comment by glen-84** [comment] 2016-02-12 11:02
@jedmao Cool, thanks guys.

I don't understand the relationship between this extension and your fork though – is this one going to be deprecated, or what is the story?

**Comment by SamVerschueren** [comment] 2016-02-12 11:04
You can think as it as the same relationship as NodeJS and io.js. Development pace and response in this repository was just to slow. Look at the open PR's. You can't blame Microsoft for it, they are working hard to make VS Code even more awesome. So as for now, the fork is being developed and released separately from this one.

**Comment by jedmao** [comment] 2016-02-12 11:56
Also, the fork is on the [official EditorConfig GitHub group](https://github.com/editorconfig?utf8=%E2%9C%93&query=vscode) and [published accordingly](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig). I would imagine that the Microsoft one will fade out of popularity as we continue to have faster iteration cycles on the fork.

**Comment by glen-84** [comment] 2016-02-12 12:16
Okay, thanks. =)

**Comment by SteveALee** [comment] 2016-03-08 18:27
Is not adding final new lined for filename beginning with '.' eg .gitignore

**Comment by SamVerschueren** [comment] 2016-03-08 19:59
Are you using the plugin from EditorConfig instead of this one? This one is deprecated...

**Comment by SteveALee** [comment] 2016-03-08 20:06
the link on the extension page brought me here!

**Comment by jedmao** [comment] 2016-03-08 20:41
@SteveALee then I believe you are using the deprecated one. See here: https://github.com/editorconfig/editorconfig-vscode/blob/master/package.json#L22

**Comment by SteveALee** [comment] 2016-03-08 20:54
thanks - I raised an issue there.
I see I clicked on the very unhelpful forked from link here
https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
It has more weight than the support link over on the right

**Closed** 2016-04-21 17:19 UTC
